import XCTest
import SnapshotTesting
import SwiftUI
import TrafaretPackageExample

/// Generated by `Trafaret`. Do not edit it directly, it may be overriden.
/// If you want to disable test generation, just use

final class ExampleViewSnapshotTest: XCTestCase {
    func test() {
        var config = ViewImageConfig.iPhone12
        config.traits = .init()

        let message = verifySnapshot(
            matching: UIHostingController(rootView: ExampleViewPreview.body),
            as: .image(on: config, perceptualPrecision: 0.9),
            originalFileName: "ExampleView",
            snapshotDirectory: ExampleViewPreview.testConfig.path.trafaretFileURL.deletingLastPathComponent().absoluteString
        )

        guard let message else { return }
        XCTFail(message)
    }
}