import XCTest
import SnapshotTesting
import SwiftUI
import TrafaretPackageExample

/// Generated by `Trafaret` in `ExampleView`.
/// Do not edit it directly, it may be overriden.
/// If you want to disable test generation, just use `trafaret` function on your preview instead of `TrafaretSnapshotProvider`
/// ```
/// body
///     .trafaret(
///         on: previewContainer,
///         compareAs: compareConfig,
///         path: path
///     )
/// ```
@available(iOS 16.0, *)
final class ExampleViewSnapshotTest: XCTestCase {
    func test() {
        var config = ViewImageConfig.iPhone12
        config.traits = .init()

        let viewController = UIHostingController(rootView: ExampleViewPreview.body)
        viewController.view.frame = CGRect(origin: .zero, size: config.size ?? .zero)

        let message = verifySnapshot(
            matching: viewController,
            as: .image(on: config, perceptualPrecision: 0.9, traits: UITraitCollection(displayScale: 3.0)),
            originalFileName: "ExampleView",
            snapshotDirectory: ExampleViewPreview.path.trafaretFileURL.deletingLastPathComponent().absoluteString
        )

        guard let message else { return }
        XCTFail(message)
    }
}